(define (make-center-width c w)
  (make-interval (- c w) (+ c w)))
(define (center i)
  (/ (+ (lower-bound i) (upper-bound i)) 2))
(define (width i)
  (/ (- (upper-bound i) (lower-bound i)) 2))
 
(define (make-center-percent c tolerance)
  (make-center-width c (* c (/ tolerance 100))))
(define (percent interval)
  (/ (* 100 (width interval))
     (center interval)))