(define (or-gate input1 input2 output)
  (let ((invert-out1 (make-wire))
        (invert-out2 (make-wire))
        (and-12 (make-wire)))
    (inverter input1 invert-out1)
    (inverter input2 invert-out2)
    (and-gate invert-out1 inver-out2 and-12)
    (inverter and-12))
  'ok)